#Browser Application
browser=chrome
url=https://www.demoblaze.com/
#Login Credentials
username=ManiNithi
password=Nithi0924
screenshotPath=C:\Users\NithiMani\Desktop\Greens Technology\MavenProject\src\Screenshots

name=Mani
country=India
city=Chennai
card=1234567890123456
month=12
year=2025